### ISSUE TITLE
Corrupted Hierarchy when moving Vertical Pane up

### ISSUE THREAD

**Issue by AMDphreak** [Metaxal/MrEd-Designer#8] opened 2019-11-13 19:24 UTC
![image](https://user-images.githubusercontent.com/1058978/68796549-b0001a80-0618-11ea-9dc0-2acb5fa35506.png)

Moved VerticalPane up (I clicked the up arrow). There was a text field above it, in the main pane. I assumed it would move the vertical pane above the text field, but it may have moved it up a level in the hierarchy, instead, putting it on the same level as the Pane.

Can't close the Project, either. When it first broke, I saved the project and closed it. It closed the Frame window and updated the Properties Window, but the Hierarchy Window was left un-updated. I exited MrEd and re-started MrEd and reopened the project, and now I can't close (unload) the project.

Command line log:
```
U:\rjamd\Google Drive\Code\repos\packet-x-ing>racket -l mred-designer
MrEd Designer 3.17: starting
template-load-file: load done
MED template version: (3 17)
send: target is not an object
  target: #f
  method name: get-text-extent
send: target is not an object
  target: #f
  method name: get-property-value
```

**Comment by Metaxal** [comment] 2019-11-16 08:36
Hi,

Thanks for the reports!

I can't yet reproduce the behaviour you had. Do you think you could send me the precise sequence of actions that led to this?

I tried:
- open mred-designer
- add frame
- click on frame
- add textfield 
- add vertical panel
- click on up arrow (up/down several times)
but all looks fine here.

Thanks!

**Comment by Metaxal** [comment] 2019-11-16 17:19
Can you check whether this is fixed with the latest commit?!

**Comment by AMDphreak** [comment] 2019-11-16 23:30
> 
> 
> Hi,
> 
> Thanks for the reports!
> 
> I can't yet reproduce the behaviour you had. Do you think you could send me the precise sequence of actions that led to this?
> 
> I tried:
> 
>     * open mred-designer
> 
>     * add frame
> 
>     * click on frame
> 
>     * add textfield
> 
>     * add vertical panel
> 
>     * click on up arrow (up/down several times)
>       but all looks fine here.
> 
> 
> Thanks!

Glad to help. Thank you for being awesome.
I'll try to reproduce it while my memory is fresh...ish. BRB.
One thing to note: I used a VerticalPane (not panel)

**Comment by AMDphreak** [comment] 2019-11-16 23:38
I think I found a (the?) source of the problem:

Inspect closely:

The Window shows Choice and Text Field.
I did:

- Add Frame.
- Add TextField.
- Add VerticalPane.
- Add Choice (below VerticalPane).
- Cut Choice.
- Paste Choice into VerticalPane (still good, no bug).
- Arrow Up the VerticalPane.

It deletes TextField from Hierarchy. Window still shows TextField, but it's below VerticalPane, so it either placed TextField below VerticalPane or it merged TextField into VerticalPane (VerticalPane Parent<-->TextField Child).

![image](https://user-images.githubusercontent.com/1058978/69000622-16df3700-0898-11ea-9016-0d488662cab9.png)


![image](https://user-images.githubusercontent.com/1058978/69000570-6a9d5080-0897-11ea-8e4a-1af67b8bd09c.png)

Also worth noting: Mouse clicks on the tree do not line up with the tree's entries, after bug happens.

**Closed as completed** 2019-11-17 09:09 UTC
Labels: bug

**Comment by Metaxal** [comment] 2019-11-17 09:11
Excellent, thanks a ton for the detailed steps! It was then very easy to reproduce and fix it. The problem was very similar to bug #7 but in a different context.

It may take a few minutes for Racket's package server to update the mred-designer package.

**Comment by AMDphreak** [comment] 2019-11-18 08:33
It works for me. Dang, that's what I call a fast bug fix.
